### ISSUE TITLE
Missing _controllerThread

### ISSUE THREAD

**Issue by krokodylowy** [rlouissidney/jip#1]
Hi

Why your version of Profiler.java doesn't contain in initProfiler section with Controller._remote?
`if (Controller._remote) {
            _controllerThread = new Thread(_controller);
            _controllerThread.start();
        }` as in jip-src-1.2
Problem https://sourceforge.net/p/jiprof/bugs/11/ doesn't occur in you version of jip?

**Comment by rlouissidney** [comment]
Hi, 
The instruction (Thread).start is  the constructor of the Remote<control class ;). I did some minor architecture change. It is not a simple upgrade. 
About the bug, if the instrumented code doesn't contains an explicit exit (System.exit(0)), the JVM doesn't stop all the threads ! And the jip continues to run.  My advice, put an explicit exit in the code.
Hope this  help ;)

**Comment by krokodylowy** [comment]
This is a webapp so I can't do any. I tested your version and the same bug  https://sourceforge.net/p/jiprof/bugs/11/  exist in your code.
