### ISSUE TITLE
All the classes that have been classloaded have been "excluded"

### ISSUE THREAD

**Issue by krokodylowy** [rlouissidney/jip#2]
I tested this version of jip at it doesn't work on configuration from original jip.
This i as webapp on Tomcat 7 with jdk 1.7. Jip targeted java 1.7.

Remote connects and starts but output xml is empty. In log I see this message

> 20:42:19,890 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3bbf4bac - Registering current configuration as safe fallback point
> Warning: a request has been made to start the profiler but no classes have been instrumented. Possible reasons:
> 1. All the classes that have been classloaded have been "excluded". Check the exclude property in the current profile properties file.
> 2. No appropriate class loader filter has been provided (see "ClassLoaderFilter.x" in the current profile properties file.) If no appropriat
> e filter can be found, the standard filter is used. Thisfilter is really only useful for stand-alone applications. Make sure your environmen
> t has a ClassLoaderFilter and that your profile properties file is configured correctly.
> 3. Sometimes when Tomcat is launched from within Eclipse, Tomcat, for some reason, will start using the appication classloader (the one that
>  stand-alone apps use) to classload the webapp rather than the web app classloader that it should use. One thing that you can try to get aro
> und this odd behavior is to not run Tomcat in debug mode (Window > Perferences > Tomcat > JVM settings : Don't run Tomcat in debug mode.) If
>  this doesn't work, you could try removing the webapp classloader filter from your profile properties file.
> No classes have been instrumented for profiling. There should be a previous message to this effect which outlines why this is happening.

But my configuration is OK. Works with old jip.

> profiler=off
> remote=on
> port=6979
> ClassLoaderFilter.1=com.mentorgen.tools.profile.instrument.clfilter.WebAppClassLoaderFilter
> ClassLoaderFilter.2=com.mentorgen.tools.profile.instrument.clfilter.StandardClassLoaderFilter
> thread-depth=compact
> thread.compact.threshold.ms=1
> max-method-count=compact
> method.compact.threshold.ms=1
> file=c:/opt/apache-tomcat-7.0.52/jip/logs
> exclude=pl.md,pl.cdm,pl.e10,pl.e15,pl.mco.AbstractMDObject,pl.mco.generatorstrategy,pl.dmt.commons.utils.DateUtils
> include=pl,org.hibernate.jpa.internal,bitronix.tm.TransactionManager,org.hibernate.event.internal.DefaultAutoFlushEventListener,org.quartz.impl.jdbcjobstore.JobStoreSupport,org.slf4j.ext.LoggerWrapper
> output=xml
> debug=off
> track.object.alloc=off

**Comment by rlouissidney** [comment]
Can you use the configuration file provided ? It is not 100% compatible with jip, see the profile directory. The classloader has been changed,it should be  :
lassLoaderFilter.1=com.mentorgen.tools.profile.instrument.classfilter.TomcatClassLoaderFilter
ClassLoaderFilter.2=com.mentorgen.tools.profile.instrument.classfilter.StandardClassLoaderFilter
Note 1 : Also see jip/src/com/mentorgen/tools/profile/instrument/classfilter/ 
Note 2.: I updated the documentation, take a look.
Note 3 : You can set the debug mode to see if the configuration is applied.
